### ISSUE TITLE
Docker routing configuration

### ISSUE THREAD

**Issue by kprinssu** [sergeycherepanov/homebrew-docker-virtualbox#5]
The official Docker app has `host.docker.internal` to expose the host system's network into hosted containers. Currently, this is not configured with docker-virtualbox as the hostname doesn't resolve to anything.

Would it be possible to set up default networking routing like the official Docker app?

**Comment by serhiicherepanov** [comment]
Hi @kprinssu 

This solution based on docker-machine and you need to look into docker-machine documentation to find a workaround. Anyway the `host.docker.internal` the mac/win specific feature, which should resolve the issue when you need access from the container to your host machine. It's not required for Linux hosts because no VM used on Linux. In this case, you able to use the Linux approach and just froward your machine port to the docker host via docker-machine ssh command.

For example https://gist.github.com/danguita/21e6f9050ef556e5e2177d8407f5a72e
